### ISSUE TITLE
The site doesn't work :/

### ISSUE THREAD

**Issue by dep1engenharia** [Babadinho/buy-sell#1]
Hello dear Babadinho!

I installed all the required node packages, and I also created my own .env config file and the site is not working. 

This is what is happening:

XXXXXXXXXXXXXXXXXXXXXXXXX/buy-sell-marketplace-main$ npm start

> buy-sell-server@1.0.0 start XXXXXXXXXXXXXXXXXXXXXXXX/buy-sell-marketplace-main
> nodemon app.js

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
Server is running on port 8000
Database Connected
GET / 404 3.467 ms - 139
GET / 404 0.273 ms - 139
GET / 404 0.381 ms - 139
GET / 404 0.272 ms - 139

When i try to access it via localhost:8000 i receive the error GET / 404 3.467 ms - 13

I'm using nodejs v12.18.04

Any guess? 

Thank you 👍

**Comment by Babadinho** [comment]
Your problem might be the REACT_APP_API=http://localhost:8000/api in your client .env. Don't forget to add /api at the end of the REACT_APP_API url.
