### ISSUE TITLE
API Server

### ISSUE THREAD

**Issue by dep1engenharia** [Babadinho/buy-sell#2]
Hello,

I manage to put the front-end up and running, but not the api server.

Can you provide me the list of variables from your .env file?
Just the names, just to make sure that i'm no missing anything.

Thanks!

**Comment by Babadinho** [comment]
Hi @dep1engenharia .env variables for server here:

LOCAL_DB=mongodb://localhost:27017/buy-sell or mongodb://0.0.0.0:27017/buy-sell
PORT=8000
CLIENT_URL=http://localhost:3000
JWT_SECRET=useanythinghere

.env for client its just: REACT_APP_API=http://localhost:8000/api
