### ISSUE TITLE
Quick Clarification :)

### ISSUE THREAD

**Issue by dep1engenharia** [Babadinho/buy-sell#3]
Hello, thank you a lot for replying :1st_place_medal: 

Just to clarify:

.env to the server:
JWT_SECRET=XX
LOCAL_DB=mongodb://localhost:27017/Mymongodb
NODE_ENV=development
CLIENT_URL=http://localhost:3000

.env for the client:
REACT_APP_API=http://localhost:8000/api

Is this correct?

###################################################################
I think that it is working:

> nodemon app.js

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
Server is running on port 8000
Database Connected
GET /api/locations 200 16.072 ms - 2
GET /api/categories 200 30.954 ms - 2
POST /api/search-results 200 26.801 ms - 2
GET /api/categories 304 4.453 ms - -
POST /api/search-results 200 8.783 ms - 2
GET /api/locations 304 3.734 ms - -
GET /api/products 200 4.916 ms - 2
GET /api/categories 304 7.150 ms - -
GET /api/locations 304 7.210 ms - -
GET /api/categories 304 4.299 ms - -
POST /api/search-results 200 4.649 ms - 2
GET /api/locations 304 2.105 ms - -
POST /api/search-results 200 4.092 ms - 2
GET /api/categories 304 4.372 ms - -
GET /api/locations 304 3.976 ms - -
POST /api/search-results 200 4.306 ms - 2
GET /api/categories 304 3.134 ms - -
GET /api/locations 304 2.955 ms - -
POST /api/login 400 12.248 ms - 35
GET /api/products 304 4.318 ms - -
GET /api/categories 304 5.819 ms - -
GET /api/locations 304 5.406 ms - -
{
  name: 'user',
  username: 'username',
  email: 'a@gmail.com',
  phone: '910000000',
  password: '123456789'
}

current errors:
Uncaught runtime errors:
×
ERROR
Network Error
    at createError (http://localhost:3000/static/js/bundle.js:44469:15)
    at XMLHttpRequest.handleError (http://localhost:3000/static/js/bundle.js:43965:14)
    
    I think that is something related with **CORS** I'll keep investigating.

**Comment by Babadinho** [comment]
Hello @dep1engenharia Yes the above is correct ad should work. The error you are getting I can't reproduce from my end as everything works fine. Are you still getting the error? Also what version of Node are you on?

**Comment by dep1engenharia** [comment]
Hello @Babadinho :)

Yeah I managed to fix it, but some APIS are not working properly, It has something to do with my database schemas, I have to re-check them all again.

I'm using node version: 12.18.4 with the respective npm.

Question, how do you acess the admin panel?
Question, 

I think you forget to mention those, and they should be place in the .env from server-side, I'm I right?
CLOUD_NAME=dcxxxxxxx
CLOUDINARY_API_KEY=39xxxxxxxxxxx
CLOUDINARY_API_SECRET=T3Yxxxxxxxxxxxxx

Thank you.

**Comment by Babadinho** [comment]
@dep1engenharia That should be http://localhost:3000/admin/dashboard.

You can modify the user model by changing the default status from 'user' to 'admin'. When you have registered as admin you can change back the status to 'user'.

You'll be able to access admin roles after you have done this.

**Comment by dep1engenharia** [comment]
Okay. Thank you.
